### ISSUE TITLE
Failing test: ValueError and Assertion - TestDirectoryRegularization

### ISSUE THREAD

**Issue by mburridge96** [iGEM-Engineering/iGEM-test-distribution-package#10]
https://github.com/iGEM-Engineering/iGEM-test-distribution-package/blob/28a69073d02f7e5e223afacafcbfec4ddd9e5928/scripts/test/test_directories.py#LL14C8-L14C61

Finds unexpected subdirectories and then continues with an assertion error 
assert str(e) == f' Could not find package excel file'

**Comment by jakebeal** [comment]
Adapted script had assumed that git and scripting directories are necessarily present. Fix is pending in branch directory-fixes.
