### ISSUE TITLE
Failing test: Assertion Error - TestImportParts

### ISSUE THREAD

**Issue by mburridge96** [iGEM-Engineering/iGEM-test-distribution-package#11]
https://github.com/iGEM-Engineering/iGEM-test-distribution-package/blob/28a69073d02f7e5e223afacafcbfec4ddd9e5928/scripts/test/test_import.py#LL43C19-L43C19

Failing due to assert len(retrieved) == 5

**Comment by jakebeal** [comment]
Importing parts and collating package needed to use full directory, not relative. Also needed to adjust tests to match current system. Fix pending.
