### ISSUE TITLE
Failing test: AssertionError - TestImportParts 

### ISSUE THREAD

**Issue by mburridge96** [iGEM-Engineering/iGEM-test-distribution-package#12]
https://github.com/iGEM-Engineering/iGEM-test-distribution-package/blob/28a69073d02f7e5e223afacafcbfec4ddd9e5928/scripts/test/test_import.py#LL32C6-L32C6

Mismatch between expected and actual. 

AssertionError: Inventory aliases do not match expected value: 
{'https://github.com/iGEM-Engineering/test_package/J23102_modified': 'https://github.com/iGEM-Engineering/test_package/J23102_modified', 'https://github.com/iGEM-Engineering/test_package/NM_005341_4': 'https://github.com/iGEM-Engineering/test_package/NM_005341_4', 'https://github.com/iGEM-Engineering/test_package/NM_005342': 'https://github.com/iGEM-Engineering/test_package/NM_005342', 'https://github.com/iGEM-Engineering/test_package/NM_005342_4': 'https://github.com/iGEM-Engineering/test_package/NM_005342', 'https://github.com/iGEM-Engineering/test_package/NM_005343': 'https://github.com/iGEM-Engineering/test_package/NM_005343', 'https://github.com/iGEM-Engineering/test_package/NM_005343_4': 'https://github.com/iGEM-Engineering/test_package/NM_005343', 'http://parts.igem.org/J23101': 'https://synbiohub.org/public/igem/BBa_J23101', 'https://synbiohub.org/public/igem/BBa_J23101': 'https://synbiohub.org/public/igem/BBa_J23101'}

**Comment by jakebeal** [comment]
Parts inventory was using directory for package, rather than Excel file. Fix is pending in branch directory-fixes.
