### ISSUE TITLE
Failing test: FileNotFoundError

### ISSUE THREAD

**Issue by mburridge96** [iGEM-Engineering/iGEM-test-distribution-package#2]
https://github.com/iGEM-Engineering/iGEM-test-distribution-package/blob/28a69073d02f7e5e223afacafcbfec4ddd9e5928/scripts/test/test_export.py#LL51C28-L51C40

Failing test due to test_package.xlsx not being found
Test Case: test_complex_sbol_export (test_export.TestExportCSV)

**Comment by jakebeal** [comment]
Adapted script had a number of path and namespace errors. Fix is pending in branch directory-fixes.
