### ISSUE TITLE
Failing test: FileNotFoundError - TestImportParts

### ISSUE THREAD

**Issue by mburridge96** [iGEM-Engineering/iGEM-test-distribution-package#5]
https://github.com/iGEM-Engineering/iGEM-test-distribution-package/blob/28a69073d02f7e5e223afacafcbfec4ddd9e5928/scripts/test/test_import.py#LL67C9-L67C9

FileNotFoundError: [Errno 2] No such file or directory: 'test_package.xlsx'
Failing due to not finding test_pacakge.xlsx. Similar fix could be applied for #3 #2

**Comment by jakebeal** [comment]
Importing parts and collating package needed to use full directory, not relative. Also needed to adjust tests to match current system. Fix pending.
