### ISSUE TITLE
Failing test: ValueError - TestMarkdownGeneration

### ISSUE THREAD

**Issue by mburridge96** [iGEM-Engineering/iGEM-test-distribution-package#6]
https://github.com/iGEM-Engineering/iGEM-test-distribution-package/blob/28a69073d02f7e5e223afacafcbfec4ddd9e5928/scripts/test/test_markdown_generation.py#LL39C9-L39C52

ValueError

**Comment by jakebeal** [comment]
Needed to stop using the old fixed namespace for searching for the build plan. Fix pending.
